name: Build and Push Docker Image
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          dao0312/statgarten:latest
          dao0312/statgarten:${{ env.RELEASE_VERSION }}
          ghcr.io/${{ github.repository_owner }}/my-container-test:latest
          ghcr.io/${{ github.repository_owner }}/my-container-test:${{ env.RELEASE_VERSION }}
        
      